spring.application.name=mbacms

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

secretKey=${JWT_SECRET}

spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB